#!/usr/bin/env bash

QUALITY=80
OPUS_BITRATE="96k"

set -euo pipefail

echo "converting img to webp..."
find . -type f \( \
    -iname "*.png" -o \
    -iname "*.jpg" -o \
    -iname "*.jpeg" \
\) | while read -r img; do
    webp="${img%.*}.webp"

    if [[ -f "$webp" ]]; then
        orig_size=$(stat -c %s "$img")
        webp_size=$(stat -c %s "$webp")

        if (( webp_size < orig_size )); then
            rm "$img"
            continue
        fi
    fi

    if cwebp -q "$QUALITY" -m "6" "$img" -o "$webp" >/dev/null; then
        rm "$img"
    else
        echo "  conversion failed: $img"
        rm -f "$webp"
    fi
done

echo "converting audio to opus..."
find . -type f \( \
    -iname "*.mp3" -o \
    -iname "*.wav" -o \
    -iname "*.flac" -o \
    -iname "*.aac" -o \
    -iname "*.m4a" -o \
    -iname "*.ogg" \
\) | while read -r audio; do
    opus="${audio%.*}.opus"

    if [[ -f "$opus" ]]; then
        continue
    fi

    if ffmpeg -nostdin -y -loglevel error \
        -i "$audio" \
        -c:a libopus \
        -b:a "$OPUS_BITRATE" \
        -application "audio" \
        "$opus"; then
        rm "$audio"
    else
        echo "  conversion failed: $audio"
        rm -f "$opus"
    fi
done

echo "updating html + md refs..."
find . -type f \( -iname "*.html" -o -iname "*.md" \) | while read -r file; do
    sed -i \
        -e 's/\.\(png\|jpg\|jpeg\)\b/.webp/gI' \
        -e 's/\.\(mp3\|wav\|flac\|aac\|m4a\|ogg\)\b/.opus/gI' \
        "$file"
done

echo "generating assets/music/playlist.json..."
PLAYLIST="assets/music/playlist.json"
{
    echo "["
    FIRST=1
    while IFS= read -r -d '' opus; do
        if [[ "$opus" =~ \.opus$ ]]; then
            if [ $FIRST -eq 1 ]; then 
                FIRST=0
            else
                echo ","
            fi
            
            echo "  {\"src\": \"$(basename "$opus")\"}"
        fi
    done < <(find "assets/music" -maxdepth 1 -type f -name "*.opus" -print0 2>/dev/null)
    echo "]"
} > "$PLAYLIST"

cd blog_src
bundle exec jekyll clean && bundle exec jekyll build
cd ..

echo "generating feed.xml..."
python3 - <<EOF
import os, re, datetime as dt

URL, SRC, OUT = "https://jackinfurs.ie", "blog_src/_posts", "feed.xml"
items = []

for f in sorted([f for f in os.listdir(SRC) if f.endswith('.md')], reverse=True)[:15]:
    slug = f.replace(".md", "")
    with open(os.path.join(SRC, f)) as s:
        c = s.read()
        d = re.search(r'^date:\s*([\d-]+)', c, re.M).group(1)
        t = "-".join(slug.split("-")[3:]).replace("-", " ")
    
    date = dt.datetime.strptime(d, "%Y-%m-%d").strftime("%a, %d %b %Y 00:00:00 +0000")
    link = f"{URL}/blog/{slug}/"
    items.append(f"<item><title><![CDATA[{t}]]></title><link>{link}</link><guid>{link}</guid><pubDate>{date}</pubDate></item>")

with open(OUT, "w") as f:
    f.write(f'<?xml version="1.0" encoding="UTF-8"?><rss version="2.0" xmlns:atom="http://www.w3.org"><channel><title>jackinfurs/blog</title><link>{URL}/blog</link><description>The blog of the personal website of Jack Dunne (jackinfurs); final year BSc. Computer Science at University College Dublin.</description><atom:link href="{URL}/feed.xml" rel="self" type="application/rss+xml" />{"".join(items)}</channel></rss>')
EOF

python3 -m http.server

